version: '3.8'

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    hostname: api
    container_name: api
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    volumes:
      - ./app:/home/app
    networks:
      - short-net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db
    networks:
      - short-net

  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis
    ports:
      - '6379:6379'
    expose:
      - '6379'
    command: redis-server
    volumes:
      - cache:/data
    networks:
      - short-net

volumes:
  mongo_data:
    driver: local

  cache:
    driver: local

networks:
  short-net:
    external: true